name: API Tests with Allure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API tests
        run: >
          mvn clean test -Dgroups=api
          -Dapi.base=https://qa-panel-assignment-214de3946f4e.herokuapp.com/api || true

      - name: Prepare Allure results
        run: mkdir -p allure-results && cp -r target/allure-results/* allure-results/ || true

      - name: Download Allure CLI
        run: |
          curl -o allure-2.24.0.zip -L https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip
          unzip allure-2.24.0.zip -d allure-cli

      - name: Generate Allure Report
        run: |
          ./allure-cli/allure-2.24.0/bin/allure generate --clean --single-file allure-results -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure Report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
